#!/usr/bin/env python
from __future__ import annotations

import json
import shutil
from pathlib import Path


SOURCE_ROOT = Path(__file__).resolve().parents[1]
OVERLEAF_ROOT = SOURCE_ROOT.parent / "alius-bulletin-overleaf-project"


def ensure_clean_dir(path: Path) -> None:
    root = SOURCE_ROOT.parent.resolve()
    target = path.resolve()
    if root not in target.parents and target != root:
        raise RuntimeError(f"Refusing to write outside {root}: {target}")
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)


def copytree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def project_path_text(text: str) -> str:
    return (
        text.replace("Path=assets/fonts/", "Path=shared-assets/fonts/")
        .replace("assets/cover-parts/", "shared-assets/cover-parts/")
        .replace("content/issues/", "issues/")
        .replace("content/pieces/", "interviews/reconstructed/")
        .replace("content/rules/", "rules/")
        .replace("% Generated by scripts/sync_issue_registry.py from issues/issue-index.json.\n", "")
    )


def copy_rewritten_file(src: Path, dst: Path) -> None:
    write_text(dst, project_path_text(read_text(src)))


def package_shared_files() -> None:
    copy_rewritten_file(SOURCE_ROOT / "aliusbulletin.cls", OVERLEAF_ROOT / "aliusbulletin.cls")
    copy_rewritten_file(SOURCE_ROOT / "project-controls.tex", OVERLEAF_ROOT / "project-controls.tex")
    copytree(SOURCE_ROOT / "assets" / "fonts", OVERLEAF_ROOT / "shared-assets" / "fonts")
    copytree(SOURCE_ROOT / "assets" / "cover-parts", OVERLEAF_ROOT / "shared-assets" / "cover-parts")
    copytree(SOURCE_ROOT / "assets" / "covers", OVERLEAF_ROOT / "shared-assets" / "covers")
    copytree(SOURCE_ROOT / "content" / "rules", OVERLEAF_ROOT / "rules")


def package_issues() -> None:
    issues_root = SOURCE_ROOT / "content" / "issues"
    target_root = OVERLEAF_ROOT / "issues"
    target_root.mkdir(parents=True, exist_ok=True)
    copy_rewritten_file(issues_root / "issue-index.json", target_root / "issue-index.json")
    for issue_dir in sorted(issues_root.glob("issue-[0-9][0-9]")):
        target_issue = target_root / issue_dir.name
        target_issue.mkdir(parents=True, exist_ok=True)
        for src in issue_dir.iterdir():
            dst = target_issue / src.name
            if src.suffix in {".tex", ".json"}:
                copy_rewritten_file(src, dst)
            elif src.name == "README.md":
                issue_number = issue_dir.name.split("-")[-1]
                write_text(
                    dst,
                    f"""# ALIUS Bulletin Issue {issue_number}

Compile this issue by editing the root `main.tex` selector:

```tex
\\input{{issues/{issue_dir.name}/main.tex}}
```

Edit this issue here:

- `cover.tex`: cover text and issue-specific metadata.
- `main.tex`: issue assembly and interview order.
- `issue.json`: structured bookkeeping.

Shared design lives in the root `project-controls.tex`.
Shared artwork and fonts live in `shared-assets`.
""",
                )
            elif src.is_file():
                shutil.copy2(src, dst)


def package_interviews() -> None:
    pieces_root = SOURCE_ROOT / "content" / "pieces"
    target_root = OVERLEAF_ROOT / "interviews" / "reconstructed"
    for piece_dir in sorted(pieces_root.iterdir()):
        if piece_dir.is_dir():
            copytree(piece_dir, target_root / piece_dir.name)


def write_project_docs() -> None:
    write_text(
        OVERLEAF_ROOT / "main.tex",
        "% ALIUS Bulletin Overleaf selector.\n"
        "% The default is a fast one-page compile so Overleaf free-plan projects do not time out on first build.\n"
        "% To compile a full issue, replace the next line with e.g. \\input{issues/issue-05/main.tex}\n"
        "\\input{compile/issue-05-cover.tex}\n",
    )
    write_text(
        OVERLEAF_ROOT / "README.md",
        """# ALIUS Bulletin Overleaf Project

This is the user-facing Overleaf project for ALIUS Bulletin issues 1-7.

## Compile

Use LuaLaTeX. The root `main.tex` is only a selector. It defaults to a fast cover compile:

```tex
\\input{compile/issue-05-cover.tex}
```

To compile a full issue, change it to an issue folder:

```tex
\\input{issues/issue-05/main.tex}
```

If Overleaf times out on a full issue, compile the cover first, clear cached files, then compile the full issue again.

## Edit An Existing Issue

- Issue assembly files live in `issues/issue-01` through `issues/issue-07`.
- Each issue has `main.tex`, `cover.tex`, `issue.json`, and a short `README.md`.
- Cover text is editable in each issue's `cover.tex`.
- Shared cover layout, typography, colors, and image paths live in `project-controls.tex`.
- Reconstructed interviews live in `interviews/reconstructed`.
- Step-by-step editing notes live in `instructions`.
- Fast cover compile shortcuts live in `compile`.

## Shared Assets

`shared-assets` is the common asset folder:

- `shared-assets/fonts`: Lato and Cormorant Garamond.
- `shared-assets/cover-parts`: editable shared cover components.
- `shared-assets/covers`: original/static cover references already present in the source project.

## Future Issues And Interviews

Blank templates live in `future`.

- Copy `future/issue-slot` to `issues/issue-08`.
- Copy `future/interview-slot` to `interviews/reconstructed/new-interview-slug`.
- Then include the new interview from the issue's `main.tex`.

## Reconstruction Status

Issues 1-4 are cover/scaffold editions with indexed interview slots, not full reconstructed bodies yet.
Issue 5 contains the currently reconstructed full issue body.
Issues 6-7 contain reconstructed available interviews plus annotated slots for missing pieces.
""",
    )
    write_text(
        OVERLEAF_ROOT / "compile" / "README.md",
        """# Compile Shortcuts

These files are user-facing shortcuts for Overleaf.

- `issue-XX-cover.tex` compiles only the generated cover.
- Full issues compile from `issues/issue-XX/main.tex`.

The root `main.tex` defaults to `issue-05-cover.tex` so upload/new-project compilation is fast.
""",
    )
    for issue in range(1, 8):
        slug = f"issue-{issue:02d}"
        write_text(
            OVERLEAF_ROOT / "compile" / f"{slug}-cover.tex",
            f"""\\documentclass{{aliusbulletin}}
\\begin{{document}}
\\input{{issues/{slug}/cover.tex}}
\\end{{document}}
""",
        )
    write_text(
        OVERLEAF_ROOT / "instructions" / "README.md",
        """# Instructions

Use these files when editing the ALIUS Bulletin Overleaf project.

- `01-compile-an-issue.md`: choose and compile an existing issue.
- `02-edit-a-cover.md`: customize cover text, issue number, dates, editors, names, colors, and artwork.
- `03-add-an-interview.md`: create a new interview/article from the empty slot.
- `04-add-a-future-issue.md`: create a future issue folder.
- `05-semantic-macros.md`: use the standardized ALIUS content macros.
- `06-asset-policy.md`: keep shared assets parsimonious.
- `07-overleaf-timeouts.md`: avoid free-plan compile timeouts.
- `08-typography-and-colors.md`: original interview typography and color rules.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "01-compile-an-issue.md",
        """# Compile An Issue

1. Open the root `main.tex`.
2. For a fast test compile, use a cover shortcut:

```tex
\\input{compile/issue-05-cover.tex}
```

3. For a full issue, change the selector line to the issue you want:

```tex
\\input{issues/issue-05/main.tex}
```

4. Compile with LuaLaTeX.

Available issue folders are `issue-01` through `issue-07`.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "02-edit-a-cover.md",
        """# Edit A Cover

Each issue cover is controlled by its own `cover.tex`.

Edit these fields inside `issues/issue-XX/cover.tex`:

```tex
\\AliusSetIssueNumber{5}
\\AliusSetIssueSpan{2021}
\\AliusSetIssueDateLine{DECEMBER 2021}
\\AliusSetIssueEditors{Editor One \\& Editor Two (eds.)}
\\AliusAddCoverSubject{SPEAKER NAME}
```

Edit shared layout and typography in `project-controls.tex`.

Edit shared images in `shared-assets/cover-parts`.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "03-add-an-interview.md",
        """# Add An Interview

1. Copy `future/interview-slot` into `interviews/reconstructed/new-interview-slug`.
2. Edit `meta.tex` for title, subtitle, authors, citation, abstract, keywords, and contributors.
3. Edit `body.tex` using semantic ALIUS macros.
4. Add the interview to an issue `main.tex`:

```tex
\\input{interviews/reconstructed/new-interview-slug/meta.tex}
\\AliusStartPiece
\\input{interviews/reconstructed/new-interview-slug/body.tex}
\\AliusFinishPiece
```

Use `\\AliusStartPieceHere` for the first piece after a cover/front-matter block.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "04-add-a-future-issue.md",
        """# Add A Future Issue

1. Copy `future/issue-slot` into `issues/issue-08`.
2. Edit `issues/issue-08/cover.tex`.
3. Add interviews to `issues/issue-08/main.tex`.
4. Change the root `main.tex` selector:

```tex
\\input{issues/issue-08/main.tex}
```

5. Compile with LuaLaTeX.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "05-semantic-macros.md",
        """# Semantic Macros

Use the shared macros instead of local formatting.

```tex
\\AliusQuestion{Question text}

\\AliusParagraph{Answer paragraph}

\\AliusSpeakerAnswer{Speaker Name}{Answer paragraph}

\\AliusPullQuote{Notable quotation}

\\AliusSectionHeading{References}

\\AliusReferenceEntry{Reference text}
```

This keeps typography, spacing, colors, citations, and future visual tuning centralized in `aliusbulletin.cls` and `project-controls.tex`.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "06-asset-policy.md",
        """# Asset Policy

Keep the project parsimonious.

- Put common fonts in `shared-assets/fonts`.
- Put reusable cover components in `shared-assets/cover-parts`.
- Put static/original cover references in `shared-assets/covers`.
- Put issue text in `issues`.
- Put interview text in `interviews/reconstructed`.
- Put future templates in `future`.

Avoid duplicating the same image in multiple issue folders. Prefer changing the shared asset once, then adjusting issue metadata.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "07-overleaf-timeouts.md",
        """# Overleaf Timeouts

If Overleaf says the compile timed out, the project is usually compiling a full issue, not a syntax-broken file.

Fast check:

```tex
\\input{compile/issue-05-cover.tex}
```

Full issue:

```tex
\\input{issues/issue-05/main.tex}
```

Recommended workflow on the free plan:

1. Compile a cover shortcut first.
2. Click `Clear cached files` if Overleaf reports stale generated files.
3. Switch the root `main.tex` selector to the full issue.
4. Recompile.

Issue 5 is currently the heaviest issue in this project. Issues 1-4 are cover/scaffold editions and compile quickly. Issues 6-7 compile faster than issue 5 because fewer reconstructed pieces are included.
""",
    )
    write_text(
        OVERLEAF_ROOT / "instructions" / "08-typography-and-colors.md",
        """# Typography And Colors

The shared class encodes the interview styles measured from the original ALIUS DOCX/PDF files.

Use semantic macros instead of local font commands:

```tex
\\AliusQuestion{Question text}
\\AliusParagraph{Answer text}
\\AliusPullQuote{Notable quotation}
```

Current shared rules:

- Questions: Lato Regular, green `#1F8135`.
- Answers: Cormorant Garamond Regular, black.
- Titles, citation, abstract, and keywords: Lato variants, black.
- Contributor names: Lato Regular, black.
- Contributor emails: Lato Light, green `#1F8135`.
- Contributor affiliations: Lato Light, black.
- Pull quote marks: Cormorant Garamond Light, gray `#595959`.
- Footers: Cormorant Garamond Light, gray `#767171`; issue-specific URL color can be set when needed.

For one-off original differences, set typography in the interview `meta.tex` before `\\AliusStartPiece`, for example:

```tex
\\AliusSetCitationTypography{12}{14}
\\AliusSetContributorTypography{12}{14}{12}{14}
\\AliusSetFooterUrlColor{AliusLinkBlue}
```

Keep new formatting changes in `aliusbulletin.cls` or `project-controls.tex` whenever they apply to more than one issue.
""",
    )
    write_text(
        OVERLEAF_ROOT / "issues" / "README.md",
        """# Issues

Each folder is one bulletin edition.

- `cover.tex`: editable issue cover metadata.
- `main.tex`: issue assembly file.
- `issue.json`: structured metadata for the issue.
- `frontmatter.tex`: present only when the issue has separate front matter.

For current work, edit individual issue folders directly. The root `main.tex` chooses which issue Overleaf compiles.
""",
    )
    write_text(
        OVERLEAF_ROOT / "interviews" / "README.md",
        """# Interviews

`reconstructed` contains interview/article bodies already converted to semantic ALIUS LaTeX.

Each interview folder uses:

- `meta.tex`: title, authors, citation, abstract, keywords, and contributor metadata.
- `body.tex`: semantic content using ALIUS macros.
- `piece.json`: structured source metadata.

Use the template in `future/interview-slot` for new interviews.
""",
    )


def write_future_slots() -> None:
    write_text(
        OVERLEAF_ROOT / "future" / "interview-slot" / "meta.tex",
        """\\AliusSetIssueNumber{8}
\\AliusSetYear{2026}
\\AliusSetPieceSlug{new-interview-slug}
\\AliusSetPieceType{interview}
\\AliusSetTitle{Interview Title}
\\AliusSetSubtitle{An interview with Speaker Name}
\\AliusSetCreditLine{By Interviewer Name}
\\AliusSetRunningTitle{Speaker Name - Interview Title}
\\AliusSetCitationLabel{Cite as:}
\\AliusSetStandaloneCitation{Speaker, S., Interviewer, I. (2026). Interview title. ALIUS Bulletin, 8.}
\\AliusSetBundleCitation{Speaker, S., Interviewer, I. (2026). Interview title. In ALIUS Bulletin, 8.}
\\AliusSetAbstract{Add the abstract here.}
\\AliusSetKeywordsLabel{Keywords:}
\\AliusSetKeywords{keyword one, keyword two}
\\AliusClearContributors
\\AliusAddContributor{Speaker Name}{speaker@example.org\\\\Institution}
\\AliusAddContributor{Interviewer Name}{interviewer@example.org\\\\Institution}
""",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "interview-slot" / "body.tex",
        """\\AliusQuestion{Add the first question here.}

\\AliusParagraph{Add the answer here.}

\\AliusPullQuote{Add a notable quotation here.}

\\AliusQuestion{Add the next question here.}

\\AliusParagraph{Continue the interview here.}

\\AliusSectionHeading{References}

\\AliusReferenceEntry{Add references here.}
""",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "interview-slot" / "piece.json",
        json.dumps(
            {
                "slug": "new-interview-slug",
                "issue": "8",
                "year": "2026",
                "type": "interview",
                "title": "Interview Title",
                "subtitle": "An interview with Speaker Name",
                "status": "template",
            },
            indent=2,
        )
        + "\n",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "interview-slot" / "README.md",
        """# Future Interview Slot

Copy this folder into `interviews/reconstructed/new-interview-slug`.

Then edit:

- `meta.tex` for title, contributors, citation, abstract, and keywords.
- `body.tex` for questions, answers, pull quotes, section headings, and references.
- `piece.json` for structured bookkeeping.

Finally, include it from an issue `main.tex`:

```tex
\\input{interviews/reconstructed/new-interview-slug/meta.tex}
\\AliusStartPiece
\\input{interviews/reconstructed/new-interview-slug/body.tex}
\\AliusFinishPiece
```
""",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "issue-slot" / "cover.tex",
        """\\input{project-controls.tex}
\\AliusSetIssueNumber{8}
\\AliusSetIssueSpan{2026}
\\AliusSetIssueDateLine{MONTH 2026}
\\AliusSetIssueWebsite{aliusresearch.org}
\\AliusSetIssueTagline{exploring the diversity of consciousness}
\\AliusSetIssueEditors{Editor One, Editor Two \\& Editor Three (eds.)}
\\AliusClearCoverSubjects
\\AliusAddCoverSubject{SPEAKER ONE}
\\AliusAddCoverSubject{SPEAKER TWO}
\\AliusAddCoverSubject{SPEAKER THREE}
\\AliusRenderIssueCover
""",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "issue-slot" / "main.tex",
        """\\documentclass{aliusbulletin}
\\begin{document}
\\AliusEnableBundleMode

\\input{issues/issue-08/cover.tex}

\\pagenumbering{arabic}
\\setcounter{page}{1}
\\hypersetup{pageanchor=true}

% Add interviews here.
% \\input{interviews/reconstructed/new-interview-slug/meta.tex}
% \\AliusStartPieceHere
% \\input{interviews/reconstructed/new-interview-slug/body.tex}
% \\AliusFinishPiece

\\end{document}
""",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "issue-slot" / "issue.json",
        json.dumps(
            {
                "issue": "8",
                "year": "2026",
                "status": "template",
                "cover": {
                    "mode": "generated",
                    "date_line": "MONTH 2026",
                    "editors": "Editor One, Editor Two & Editor Three (eds.)",
                    "subjects": ["Speaker One", "Speaker Two", "Speaker Three"],
                },
                "pieces": [],
            },
            indent=2,
        )
        + "\n",
    )
    write_text(
        OVERLEAF_ROOT / "future" / "issue-slot" / "README.md",
        """# Future Issue Slot

Copy this folder to `issues/issue-08`.

Then:

1. Edit `cover.tex` for cover metadata.
2. Edit `main.tex` to include reconstructed interviews.
3. Edit `issue.json` for bookkeeping.
4. In the root `main.tex`, change the selector to `\\input{issues/issue-08/main.tex}`.
""",
    )


def main() -> None:
    ensure_clean_dir(OVERLEAF_ROOT)
    package_shared_files()
    package_issues()
    package_interviews()
    write_project_docs()
    write_future_slots()
    print(f"Packaged Overleaf project at {OVERLEAF_ROOT}")


if __name__ == "__main__":
    main()
