#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


RECONSTRUCTED_STATUS = "reconstructed"


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in str(text))


def piece_is_reconstructed(root: Path, piece: dict[str, Any]) -> bool:
    if piece.get("status") != RECONSTRUCTED_STATUS:
        return False
    content_dir = piece.get("content_dir")
    if not content_dir:
        return False
    content_path = root / content_dir
    return (content_path / "meta.tex").exists() and (content_path / "body.tex").exists()


def issue_progress(root: Path, issue: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    reconstructed = []
    missing = []
    for piece in issue.get("pieces", []):
        if piece_is_reconstructed(root, piece):
            reconstructed.append(piece)
        else:
            missing.append(piece)
    return reconstructed, missing


def issue_json_content(issue: dict[str, Any]) -> str:
    return json.dumps(issue, indent=2, ensure_ascii=True) + "\n"


def issue_readme_content(issue: dict[str, Any], reconstructed: list[dict[str, Any]], missing: list[dict[str, Any]]) -> str:
    lines = [
        f"# ALIUS Bulletin {issue['issue_number']}",
        "",
        f"- Year: `{issue['year']}`",
        f"- Reconstruction status: `{issue['status']}`",
        f"- Reference PDF: `{issue['reference_pdf']}`",
        f"- Source page: `{issue.get('source_page', 'not indexed')}`",
        f"- Cover mode: `{issue.get('cover', {}).get('mode', 'static-or-scaffold')}`",
        f"- Reconstructed pieces: `{len(reconstructed)}`",
        f"- Indexed pieces still needing reconstruction: `{len(missing)}`",
        "",
        "## Pieces",
        "",
    ]
    for piece in issue.get("pieces", []):
        status = "reconstructed" if piece in reconstructed else piece.get("status", "source-indexed")
        lines.append(f"- `{piece['slug']}` - {piece['title']} (`{status}`)")
    lines.extend(
        [
            "",
            "## Build",
            "",
            f"Set `content/issues/{issue['name']}/main.tex` as the Overleaf main file, or compile `fixtures/issues/{issue['name']}.tex` from the project root.",
            "",
        ]
    )
    return "\n".join(lines)


def cover_tex_content(issue: dict[str, Any]) -> str | None:
    cover = issue.get("cover")
    if not cover or cover.get("mode") != "generated":
        return None
    lines = [
        r"% Generated by scripts/sync_issue_registry.py from content/issues/issue-index.json.",
        r"% Edit issue cover metadata in the registry, or override layout in project-controls.tex.",
        r"\input{project-controls.tex}",
        r"\AliusSetIssueNumber{" + str(issue["issue_number"]) + r"}",
        r"\AliusSetIssueSpan{" + str(issue.get("year", "")) + r"}",
        r"\AliusSetIssueDateLine{" + cover.get("date_line", "") + r"}",
        r"\AliusSetIssueWebsite{" + cover.get("website", "aliusresearch.org") + r"}",
        r"\AliusSetIssueTagline{" + cover.get("tagline", "exploring the diversity of consciousness") + r"}",
        r"\AliusSetIssueEditors{" + cover.get("editors", "") + r"}",
        r"\AliusClearCoverSubjects",
    ]
    for subject in cover.get("subjects", []):
        lines.append(r"\AliusAddCoverSubject{" + subject + r"}")
    lines.extend([r"\AliusRenderIssueCover", ""])
    return "\n".join(lines)


def scaffold_note(issue: dict[str, Any], missing: list[dict[str, Any]]) -> str:
    if not missing:
        return "All indexed pieces for this issue have reconstructed TeX sources."
    missing_slugs = ", ".join(piece["slug"] for piece in missing)
    return (
        "This issue folder is an assembly scaffold. The missing indexed pieces are: "
        f"{missing_slugs}. Reconstruct each missing piece into content/pieces/<slug>/meta.tex "
        "and body.tex, then rerun scripts/sync_issue_registry.py."
    )


def issue_main_tex(root: Path, issue: dict[str, Any], reconstructed: list[dict[str, Any]], missing: list[dict[str, Any]]) -> str:
    has_generated_cover = cover_tex_content(issue) is not None
    lines = [
        r"\documentclass{aliusbulletin}",
        r"% Generated by scripts/sync_issue_registry.py from content/issues/issue-index.json.",
        r"\begin{document}",
        r"\AliusEnableBundleMode",
        f"% Reference PDF: {issue['reference_pdf']}",
        f"% Source page: {issue.get('source_page', 'not indexed')}",
        "",
    ]
    if has_generated_cover:
        lines.append(r"\input{content/issues/" + issue["name"] + r"/cover.tex}")
        lines.append("")
    frontmatter = issue.get("frontmatter")
    if frontmatter and (root / frontmatter).exists():
        lines.append(r"\hypersetup{pageanchor=false}")
        lines.append(r"\input{" + frontmatter + "}")
    elif not has_generated_cover:
        lines.append(
            r"\AliusIssueScaffoldPage{ALIUS Bulletin n\textdegree\ "
            + tex_escape(issue["issue_number"])
            + r"}{"
            + tex_escape(f"{issue['year']} reconstruction scaffold")
            + r"}{"
            + tex_escape(scaffold_note(issue, missing))
            + r"}"
        )
    lines.extend(
        [
            "",
            r"\pagenumbering{arabic}",
            r"\setcounter{page}{1}",
            r"\hypersetup{pageanchor=true}",
            "",
        ]
    )
    if missing:
        lines.append(r"% Uncomment the next two lines to render editor-only reconstruction notes.")
        lines.append(r"% \AliusShowRuleAnnotations")
        lines.append(r"% \input{content/rules/bulletin-rules.tex}")
        for piece in missing:
            lines.append(
                r"\AliusRuleAnnotation{Indexed but not yet reconstructed: "
                + tex_escape(piece["slug"])
                + r" -- "
                + tex_escape(piece["title"])
                + r".}"
            )
        lines.append("")
    for index, piece in enumerate(reconstructed):
        content_dir = piece["content_dir"].replace("\\", "/")
        lines.append(r"\input{" + content_dir + r"/meta.tex}")
        lines.append(r"\AliusStartPieceHere" if index == 0 else r"\AliusStartPiece")
        lines.append(r"\input{" + content_dir + r"/body.tex}")
        lines.append(r"\AliusFinishPiece")
        lines.append("")
    lines.append(r"\end{document}")
    lines.append("")
    return "\n".join(lines)


def fixture_tex(issue: dict[str, Any]) -> str:
    return "\n".join(
        [
            r"% Generated by scripts/sync_issue_registry.py.",
            r"\input{content/issues/" + issue["name"] + r"/main.tex}",
            "",
        ]
    )


def cover_fixture_tex(issue: dict[str, Any]) -> str:
    return "\n".join(
        [
            r"% Generated by scripts/sync_issue_registry.py.",
            r"\documentclass{aliusbulletin}",
            r"\begin{document}",
            r"\input{content/issues/" + issue["name"] + r"/cover.tex}",
            r"\end{document}",
            "",
        ]
    )


def manifest_entry_for_piece(piece: dict[str, Any], required_fonts: list[str]) -> dict[str, Any]:
    slug = piece["slug"]
    return {
        "name": slug,
        "main_tex": f"fixtures/pieces/{slug}.tex",
        "content_dir": piece["content_dir"],
        "reference_pdf": piece.get("reference_pdf", ""),
        "required_fonts": required_fonts,
        "status": piece.get("status", "source-indexed"),
    }


def manifest_entry_for_issue(issue: dict[str, Any], required_fonts: list[str]) -> dict[str, Any]:
    return {
        "name": issue["name"],
        "main_tex": f"fixtures/issues/{issue['name']}.tex",
        "reference_pdf": issue.get("reference_pdf", ""),
        "required_fonts": required_fonts,
        "status": issue.get("status", "source-indexed"),
    }


def all_issues_manifest(root: Path, registry: dict[str, Any]) -> str:
    required_fonts = registry.get("default_required_fonts", [])
    piece_entries: list[dict[str, Any]] = []
    issue_entries: list[dict[str, Any]] = []
    seen_pieces: set[str] = set()
    for issue in registry.get("issues", []):
        issue_entries.append(manifest_entry_for_issue(issue, required_fonts))
        for piece in issue.get("pieces", []):
            if piece.get("slug") in seen_pieces or not piece_is_reconstructed(root, piece):
                continue
            piece_entries.append(manifest_entry_for_piece(piece, required_fonts))
            seen_pieces.add(piece["slug"])
    return json.dumps({"pieces": piece_entries, "issues": issue_entries}, indent=2, ensure_ascii=True) + "\n"


def sync(registry_path: Path) -> list[Path]:
    root = project_root()
    registry = read_json(registry_path)
    changed: list[Path] = []
    for issue in registry.get("issues", []):
        reconstructed, missing = issue_progress(root, issue)
        issue_dir = root / "content" / "issues" / issue["name"]
        writes = {
            issue_dir / "issue.json": issue_json_content(issue),
            issue_dir / "README.md": issue_readme_content(issue, reconstructed, missing),
            issue_dir / "main.tex": issue_main_tex(root, issue, reconstructed, missing),
            root / "fixtures" / "issues" / f"{issue['name']}.tex": fixture_tex(issue),
        }
        cover_content = cover_tex_content(issue)
        if cover_content is not None:
            writes[issue_dir / "cover.tex"] = cover_content
            writes[root / "fixtures" / "covers" / f"{issue['name']}-cover.tex"] = cover_fixture_tex(issue)
        for path, content in writes.items():
            if write_if_changed(path, content):
                changed.append(path)
    all_manifest = root / "fixtures" / "all-issues-manifest.json"
    if write_if_changed(all_manifest, all_issues_manifest(root, registry)):
        changed.append(all_manifest)
    return changed


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync issue folders and manifests from the ALIUS Bulletin issue registry.")
    parser.add_argument(
        "--registry",
        type=Path,
        default=project_root() / "content" / "issues" / "issue-index.json",
        help="Path to content/issues/issue-index.json.",
    )
    args = parser.parse_args()
    changed = sync(args.registry.resolve())
    if changed:
        print("Updated:")
        for path in changed:
            print(f"- {path.relative_to(project_root())}")
    else:
        print("Issue registry already in sync.")


if __name__ == "__main__":
    main()
